import { ShapeKind } from "shared";
import type { AttackAbility, MoveAbility, RestoreAbility, SpriteSet, UnitTemplate, ItemDefinition, ZoneAbility } from "shared";
import type { StructureEntry } from "shared";
import { saveDimension, saveEnemyTemplates, saveItems, withStructureIndices } from "./db.js";

function enemySprites(dimension: number, name: string): SpriteSet {
  const base = `/api/sprites/enemies/dimension-${dimension}/${name}/${name}`;
  return {
    idle: `${base}-idle.webp`,
    attack: `${base}-attack.webp`,
    hit: `${base}-hit.webp`,
    move: `${base}-move.webp`,
  };
}

// --- Enemy Abilities (dimension 0) ---

function makeMove(distance: number): MoveAbility {
  return { id: "move", name: "Move", kind: "move", cost: { blue: 1 }, distance };
}

const GOBLIN_SPEAR_THRUST: AttackAbility = {
  id: "goblin-spear-thrust",
  name: "Spear Thrust",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Rectangle, length: 100, width: 18 },
  damage: 25,
  knockback: 20,
  visual: { color: 0xa89070, trailEffect: "thrust", screenShake: 0.2 },
};

const GOBLIN_BOW_SHOT: AttackAbility = {
  id: "goblin-bow-shot",
  name: "Bow Shot",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Point, range: 260 },
  damage: 15,
  knockback: 0,
  visual: { color: 0xd4a857, trailEffect: "projectile" },
};

const SHIELD_BASH_ATTACK: AttackAbility = {
  id: "shield-bash",
  name: "Shield Bash",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Sector, radius: 60, halfAngle: Math.PI / 4 },
  damage: 15,
  knockback: 45,
  visual: { color: 0x8899aa, trailEffect: "slash", screenShake: 0.35 },
};

const BRUTE_SLAM_ATTACK: AttackAbility = {
  id: "brute-slam",
  name: "Brute Slam",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Sector, radius: 90, halfAngle: Math.PI / 2 },
  damage: 40,
  knockback: 50,
  visual: { color: 0x7a6040, trailEffect: "slash", screenShake: 0.6 },
};

const GOLEM_SMASH_ATTACK: AttackAbility = {
  id: "golem-smash",
  name: "Golem Smash",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Circle, radius: 70, range: 60 },
  damage: 50,
  knockback: 60,
  visual: { color: 0x8b7355, trailEffect: "explosion", screenShake: 0.8 },
};

const SLIME_SPIT_ATTACK: AttackAbility = {
  id: "slime-spit",
  name: "Slime Spit",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Point, range: 180 },
  damage: 12,
  knockback: 0,
  visual: { color: 0x5cb85c, trailEffect: "projectile" },
};

const SLIME_LASH_ATTACK: AttackAbility = {
  id: "slime-lash",
  name: "Slime Lash",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Sector, radius: 70, halfAngle: Math.PI / 3 },
  damage: 20,
  knockback: 20,
  visual: { color: 0x5cb85c, trailEffect: "splash", screenShake: 0.2 },
};

const SLIME_WAVE_ATTACK: AttackAbility = {
  id: "slime-wave",
  name: "Slime Wave",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Circle, radius: 80, range: 50 },
  damage: 35,
  knockback: 35,
  visual: { color: 0x5cb85c, trailEffect: "splash", screenShake: 0.5 },
};

// --- Enemy Templates (dimension 0) ---

const ENEMY_TEMPLATES: Record<string, UnitTemplate> = {
  "goblin-spear": {
    abilities: [makeMove(150), GOBLIN_SPEAR_THRUST],
    hp: 80,
    energy: { red: 1, blue: 1 },
    collisionRadius: 14,
    className: "Goblin Spearman",
    sprites: enemySprites(0, "goblin-spear"),
    heightMeters: 1.5,
    strategy: "rush",
    cost: 3,
    tags: ["melee"],
  },
  "goblin-archer": {
    abilities: [makeMove(140), GOBLIN_BOW_SHOT],
    hp: 55,
    energy: { red: 1, blue: 2 },
    collisionRadius: 12,
    className: "Goblin Archer",
    sprites: enemySprites(0, "goblin-archer"),
    heightMeters: 1.5,
    strategy: "kite",
    cost: 3,
    tags: ["ranged"],
  },
  "goblin-shield": {
    abilities: [makeMove(110), SHIELD_BASH_ATTACK],
    hp: 110,
    energy: { red: 1, blue: 2 },
    collisionRadius: 16,
    className: "Goblin Shield",
    sprites: enemySprites(0, "goblin-shield"),
    heightMeters: 1.5,
    strategy: "rush",
    cost: 4,
    tags: ["melee", "tank"],
  },
  "goblin-brute": {
    abilities: [makeMove(90), BRUTE_SLAM_ATTACK],
    hp: 160,
    energy: { red: 1, blue: 1 },
    collisionRadius: 20,
    className: "Goblin Brute",
    sprites: enemySprites(0, "goblin-brute"),
    heightMeters: 1.75,
    strategy: "rush",
    cost: 6,
    tags: ["melee", "elite"],
  },
  "stone-golem": {
    abilities: [makeMove(70), GOLEM_SMASH_ATTACK],
    hp: 250,
    energy: { red: 1, blue: 1 },
    collisionRadius: 22,
    className: "Stone Golem",
    sprites: enemySprites(0, "stone-golem"),
    heightMeters: 3,
    strategy: "threat",
    cost: 10,
    tags: ["melee", "tank", "boss"],
  },
  "slime": {
    abilities: [makeMove(120), SLIME_SPIT_ATTACK],
    hp: 40,
    energy: { red: 1, blue: 2 },
    collisionRadius: 12,
    className: "Slime",
    sprites: enemySprites(0, "slime"),
    heightMeters: 1.5,
    strategy: "kite",
    cost: 1,
    tags: ["ranged", "swarm"],
  },
  "big-slime": {
    abilities: [makeMove(100), SLIME_LASH_ATTACK],
    hp: 90,
    energy: { red: 1, blue: 2 },
    collisionRadius: 18,
    className: "Big Slime",
    sprites: enemySprites(0, "slime"),
    heightMeters: 3,
    strategy: "rush",
    effects: [{ trigger: "onDeath", action: { type: "spawn", templateKey: "slime", count: 2 } }],
    cost: 6,
    tags: ["melee", "tank", "elite"],
  },
  "massive-slime": {
    abilities: [makeMove(70), SLIME_WAVE_ATTACK],
    hp: 200,
    energy: { red: 1, blue: 1 },
    collisionRadius: 28,
    className: "Massive Slime",
    sprites: enemySprites(0, "slime"),
    heightMeters: 6,
    strategy: "threat",
    effects: [{ trigger: "onDeath", action: { type: "spawn", templateKey: "big-slime", count: 2 } }],
    cost: 14,
    tags: ["melee", "tank", "boss"],
  },
};

// --- Dimension 0 Structures ---

function dim0Sprite(folder: string, name: string): string {
  const sub = folder ? `${folder}/` : "";
  return `sprites/map-objects/${sub}${name}.webp`;
}

const DIMENSION_0_STRUCTURES: StructureEntry[] = withStructureIndices([
  { name: "tree-oak-small", cost: 1, scale: 0.35, spritePath: dim0Sprite("plants", "tree-oak-small") },
  { name: "tree-oak-medium", cost: 2, scale: 0.4, spritePath: dim0Sprite("plants", "tree-oak-medium") },
  { name: "tree-oak-large", cost: 3, scale: 0.45, spritePath: dim0Sprite("plants", "tree-oak-large") },
  { name: "tree-pine", cost: 2, scale: 0.45, spritePath: dim0Sprite("plants", "tree-pine") },
  { name: "bush-small", cost: 1, scale: 0.3, spritePath: dim0Sprite("plants", "bush-small") },
  { name: "bush-medium", cost: 1, scale: 0.35, spritePath: dim0Sprite("plants", "bush-medium") },
  { name: "bush-large", cost: 2, scale: 0.35, spritePath: dim0Sprite("plants", "bush-large") },
  { name: "grass-small", cost: 1, scale: 0.25, spritePath: dim0Sprite("plants", "grass-small") },
  { name: "grass-medium", cost: 1, scale: 0.25, spritePath: dim0Sprite("plants", "grass-medium") },
  { name: "grass-large", cost: 1, scale: 0.3, spritePath: dim0Sprite("plants", "grass-large") },
  { name: "rock-small", cost: 1, scale: 0.25, spritePath: dim0Sprite("rocks", "rock-small") },
  { name: "rock-medium", cost: 2, scale: 0.3, spritePath: dim0Sprite("rocks", "rock-medium") },
  { name: "rock-large", cost: 3, scale: 0.35, spritePath: dim0Sprite("rocks", "rock-large") },
  { name: "rock-pile", cost: 2, scale: 0.3, spritePath: dim0Sprite("rocks", "rock-pile") },
  { name: "ruins-rubble", cost: 2, scale: 0.35, spritePath: dim0Sprite("", "ruins-rubble") },
  { name: "stone-block", cost: 2, scale: 0.25, spritePath: dim0Sprite("walls", "stone-block") },
  { name: "stone-brick", cost: 2, scale: 0.25, spritePath: dim0Sprite("walls", "stone-brick") },
  { name: "stone-pillar", cost: 3, scale: 0.3, spritePath: dim0Sprite("walls", "stone-pillar") },
  { name: "wall-corner", cost: 3, scale: 0.3, spritePath: dim0Sprite("walls", "wall-corner") },
  { name: "wall-enclosure", cost: 4, scale: 0.35, spritePath: dim0Sprite("walls", "wall-enclosure") },
  { name: "wall-long", cost: 3, scale: 0.3, spritePath: dim0Sprite("walls", "wall-long") },
  { name: "wall-medium", cost: 2, scale: 0.3, spritePath: dim0Sprite("walls", "wall-medium") },
  { name: "wall-short", cost: 1, scale: 0.25, spritePath: dim0Sprite("walls", "wall-short") },
  { name: "wall-t-junction", cost: 3, scale: 0.3, spritePath: dim0Sprite("walls", "wall-t-junction") },
  { name: "wall-u-shape", cost: 3, scale: 0.3, spritePath: dim0Sprite("walls", "wall-u-shape") },
]);

// --- Weapon Abilities (dimension 0) ---

const SHORT_SWORD_SLASH: AttackAbility = {
  id: "short-sword-slash",
  name: "Slash",
  kind: "attack",
  cost: { red: 2 },
  shape: { kind: ShapeKind.Sector, radius: 80, halfAngle: Math.PI / 3 },
  damage: 25,
  knockback: 30,
  visual: { color: 0xc0c0c0, trailEffect: "slash", screenShake: 0.3 },
};

const SHORT_SWORD_STAB: AttackAbility = {
  id: "short-sword-stab",
  name: "Stab",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Rectangle, length: 90, width: 12 },
  damage: 11,
  knockback: 0,
  visual: { color: 0xc0c0c0, trailEffect: "thrust" },
};

const SPEAR_THRUST: AttackAbility = {
  id: "spear-thrust",
  name: "Thrust",
  kind: "attack",
  cost: { red: 2 },
  shape: { kind: ShapeKind.Rectangle, length: 140, width: 20 },
  damage: 32,
  knockback: 25,
  visual: { color: 0xa89070, trailEffect: "thrust", screenShake: 0.3 },
};

const SPEAR_JAB: AttackAbility = {
  id: "spear-jab",
  name: "Shaft Strike",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Sector, radius: 55, halfAngle: Math.PI / 4 },
  damage: 10,
  knockback: 45,
  visual: { color: 0xa89070, trailEffect: "slash", screenShake: 0.2 },
};

const BOW_SHOT: AttackAbility = {
  id: "bow-shot",
  name: "Shot",
  kind: "attack",
  cost: { red: 2 },
  shape: { kind: ShapeKind.Point, range: 300 },
  damage: 25,
  knockback: 0,
  ignoreCoverRange: 40,
  visual: { color: 0xd4a857, trailEffect: "projectile", screenShake: 0.15 },
};

const BOW_VOLLEY: AttackAbility = {
  id: "bow-volley",
  name: "Volley",
  kind: "attack",
  cost: { red: 1 },
  shape: { kind: ShapeKind.Circle, radius: 40, range: 250 },
  damage: 12,
  knockback: 0,
  visual: { color: 0xd4a857, trailEffect: "projectile", screenShake: 0.1 },
};

// --- Items (dimension 0) ---

// Debug-only weapon: every new combat mechanic on one stick, cheap to use, so each can be tried
// in isolation. Prepended to the starting bag in server/src/index.ts.
const ABILITY_TEST_WEAPON: ItemDefinition = {
  type: "weapon",
  id: "abilitytest",
  name: "Test Rod",
  description: "Debug weapon — exercises every new ability mechanic.",
  rarity: "common",
  sprite: "short-sword",
  dimensionId: 0,
  slotCost: { hand: 1 },
  animSet: "sword",
  abilities: [
    {
      id: "test-slam", name: "Wall Slam", kind: "attack", cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 90, width: 24 },
      damage: 12, knockback: 90, wallSlamDamage: 25,
      visual: { color: 0xcaa15a, trailEffect: "thrust", screenShake: 0.3 },
    } satisfies AttackAbility,
    {
      id: "test-recoil", name: "Recoil Blast", kind: "attack", cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 70, halfAngle: Math.PI / 3 },
      damage: 12, knockback: 25, recoil: 55,
      visual: { color: 0xcaa15a, trailEffect: "explosion", screenShake: 0.4 },
    } satisfies AttackAbility,
    {
      id: "test-lunge", name: "Lunge Strike", kind: "attack", cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 80, width: 18 },
      damage: 12, knockback: 0, lungeThrough: 100,
      visual: { color: 0xcaa15a, trailEffect: "thrust", screenShake: 0.2 },
    } satisfies AttackAbility,
    {
      id: "test-root", name: "Root Shot", kind: "attack", cost: { red: 1 },
      shape: { kind: ShapeKind.Point, range: 280 },
      damage: 8, knockback: 0, onHit: [{ type: "applyStatus", status: "rooted", duration: 2, value: 1 }],
      visual: { color: 0xcaa15a, trailEffect: "projectile", screenShake: 0.1 },
    } satisfies AttackAbility,
    { id: "test-zone-damage", name: "Damage Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "damage", radius: 60, duration: 3, magnitude: 12, color: 0xc0392b } } satisfies ZoneAbility,
    { id: "test-zone-heal", name: "Heal Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "heal", radius: 60, duration: 3, magnitude: 15, color: 0x2ecc71 } } satisfies ZoneAbility,
    { id: "test-zone-barrier", name: "Barrier Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "addBarrier", radius: 60, duration: 3, magnitude: 12, color: 0x3498db } } satisfies ZoneAbility,
    { id: "test-zone-drain-red", name: "Drain Attack Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "drainRed", radius: 60, duration: 3, magnitude: 1, color: 0xe67e22 } } satisfies ZoneAbility,
    { id: "test-zone-drain-blue", name: "Drain Move Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "drainBlue", radius: 60, duration: 3, magnitude: 1, color: 0x5b9bd5 } } satisfies ZoneAbility,
    { id: "test-zone-cover", name: "Cover Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "cover", radius: 50, duration: 4, magnitude: 0, color: 0x8b7355 } } satisfies ZoneAbility,
    { id: "test-zone-wall", name: "Wall Zone", kind: "zone", cost: { blue: 1 }, range: 220,
      zone: { effect: "wall", radius: 40, duration: 4, magnitude: 0, color: 0x555555 } } satisfies ZoneAbility,
  ],
};

const DIMENSION_0_ITEMS: Record<string, ItemDefinition> = {
  "abilitytest": ABILITY_TEST_WEAPON,
  "short-sword": {
    type: "weapon",
    id: "short-sword",
    name: "Short Sword",
    description: "A light blade suited for quick strikes.",
    rarity: "common",
    sprite: "short-sword",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [SHORT_SWORD_SLASH, SHORT_SWORD_STAB],
    animSet: "sword",
    visualScale: 2.0,
  },
  "long-sword": {
    type: "weapon",
    id: "long-sword",
    name: "Long Sword",
    description: "A versatile blade with good reach and damage.",
    rarity: "uncommon",
    sprite: "long-sword",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "long-sword-slash",
      name: "Long Slash",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Sector, radius: 100, halfAngle: Math.PI / 3 },
      damage: 35,
      knockback: 35,
      visual: { color: 0xc0c0c0, trailEffect: "slash", screenShake: 0.35 },
    } satisfies AttackAbility, {
      id: "long-sword-halfsword",
      name: "Half-sword",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 65, width: 22 },
      damage: 20,
      knockback: 0,
      visual: { color: 0xc0c0c0, trailEffect: "thrust", screenShake: 0.2 },
    } satisfies AttackAbility, {
      id: "long-sword-crosscut",
      name: "Cross-cut",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 80, halfAngle: Math.PI / 2 },
      damage: 14,
      knockback: 0,
      visual: { color: 0xc0c0c0, trailEffect: "slash", screenShake: 0.15 },
    } satisfies AttackAbility],
    animSet: "sword",
  },
  "spear": {
    type: "weapon",
    id: "spear",
    name: "Spear",
    description: "A long polearm with superior reach.",
    rarity: "common",
    sprite: "spear",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [SPEAR_THRUST, SPEAR_JAB],
    animSet: "spear",
  },
  "axe": {
    type: "weapon",
    id: "axe",
    name: "Axe",
    description: "A brutal chopping weapon that hits hard.",
    rarity: "common",
    sprite: "axe",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "axe-chop",
      name: "Chop",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Sector, radius: 75, halfAngle: Math.PI / 6 },
      damage: 40,
      knockback: 40,
      visual: { color: 0x9a8060, trailEffect: "slash", screenShake: 0.45 },
    } satisfies AttackAbility, {
      id: "axe-hack",
      name: "Hack",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 70, halfAngle: Math.PI / 2 },
      damage: 16,
      knockback: 0,
      visual: { color: 0x9a8060, trailEffect: "slash", screenShake: 0.2 },
    } satisfies AttackAbility],
    animSet: "sword",
    visualScale: 4,
  },
  "bow": {
    type: "weapon",
    id: "bow",
    name: "Bow",
    description: "A ranged weapon that fires arrows at distant targets.",
    rarity: "common",
    sprite: "bow",
    dimensionId: 0,
    slotCost: { hand: 2 },
    abilities: [BOW_SHOT, {
      id: "bow-piercing-arrow",
      name: "Piercing Arrow",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 220, width: 14 },
      damage: 10,
      knockback: 0,
      visual: { color: 0xd4a857, trailEffect: "projectile", screenShake: 0.1 },
    } satisfies AttackAbility],
    animSet: "bow",
  },
  "broadsword": {
    type: "weapon",
    id: "broadsword",
    name: "Broadsword",
    description: "A heavy blade with a wide sweeping arc.",
    rarity: "uncommon",
    sprite: "broadsword",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "broadsword-sweep",
      name: "Sweep",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Sector, radius: 90, halfAngle: Math.PI / 2 },
      damage: 30,
      knockback: 30,
      visual: { color: 0xb0b0b0, trailEffect: "slash", screenShake: 0.5 },
    } satisfies AttackAbility, {
      id: "broadsword-halfsword",
      name: "Half-sword",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Rectangle, length: 115, width: 18 },
      damage: 42,
      knockback: 0,
      visual: { color: 0xb0b0b0, trailEffect: "thrust", screenShake: 0.4 },
    } satisfies AttackAbility, {
      id: "broadsword-pommel-strike",
      name: "Pommel Strike",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 50, halfAngle: Math.PI / 4 },
      damage: 12,
      knockback: 60,
      visual: { color: 0xb0b0b0, trailEffect: "slash", screenShake: 0.3 },
    } satisfies AttackAbility],
    animSet: "two-handed",
  },
  "battle-axe": {
    type: "weapon",
    id: "battle-axe",
    name: "Battle Axe",
    description: "A massive axe that cleaves through armor.",
    rarity: "rare",
    sprite: "battle-axe",
    dimensionId: 0,
    slotCost: { hand: 2 },
    abilities: [{
      id: "battle-axe-cleave",
      name: "Cleave",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Sector, radius: 85, halfAngle: Math.PI / 3 },
      damage: 45,
      knockback: 50,
      visual: { color: 0x8a7050, trailEffect: "slash", screenShake: 0.6 },
    } satisfies AttackAbility, {
      id: "battle-axe-hook",
      name: "Hook",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 90, width: 35 },
      damage: 14,
      knockback: 75,
      visual: { color: 0x8a7050, trailEffect: "slash", screenShake: 0.35 },
    } satisfies AttackAbility, {
      id: "battle-axe-rend",
      name: "Rend",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 80, halfAngle: Math.PI / 2 },
      damage: 20,
      knockback: 0,
      visual: { color: 0x8a7050, trailEffect: "slash", screenShake: 0.3 },
    } satisfies AttackAbility],
    animSet: "two-handed",
  },
  "mace": {
    type: "weapon",
    id: "mace",
    name: "Mace",
    description: "A spiked bludgeon that delivers crushing blows.",
    rarity: "uncommon",
    sprite: "mace",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "mace-crush",
      name: "Crush",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Sector, radius: 70, halfAngle: Math.PI / 4 },
      damage: 30,
      knockback: 55,
      recoil: 30,
      visual: { color: 0x707070, trailEffect: "explosion", screenShake: 0.5 },
    } satisfies AttackAbility, {
      id: "mace-overhead",
      name: "Overhead Strike",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Circle, radius: 55, range: 0 },
      damage: 18,
      knockback: 0,
      visual: { color: 0x707070, trailEffect: "explosion", screenShake: 0.35 },
    } satisfies AttackAbility, {
      id: "mace-lunge",
      name: "Lunge",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Rectangle, length: 85, width: 20 },
      damage: 15,
      knockback: 35,
      lungeThrough: 95,
      visual: { color: 0x707070, trailEffect: "thrust", screenShake: 0.25 },
    } satisfies AttackAbility],
    animSet: "sword",
  },
  "round-shield": {
    type: "shield",
    id: "round-shield",
    name: "Round Shield",
    description: "A simple wooden shield that blocks incoming damage.",
    rarity: "common",
    sprite: "round-shield",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "round-shield-block",
      name: "Block",
      kind: "barrier",
      cost: { blue: 1 },
      barrierHp: 10,
    }, {
      id: "round-shield-bash",
      name: "Shield Bash",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 55, halfAngle: Math.PI / 4 },
      damage: 12,
      knockback: 40,
      visual: { color: 0x8899aa, trailEffect: "slash", screenShake: 0.3 },
    } satisfies AttackAbility],
  },
  "kite-shield": {
    type: "shield",
    id: "kite-shield",
    name: "Kite Shield",
    description: "A sturdy metal shield offering strong protection.",
    rarity: "uncommon",
    sprite: "kite-shield",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "kite-shield-block",
      name: "Block",
      kind: "barrier",
      cost: { blue: 1 },
      barrierHp: 15,
    }, {
      id: "kite-shield-bash",
      name: "Shield Bash",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 65, halfAngle: Math.PI / 4 },
      damage: 15,
      knockback: 50,
      visual: { color: 0x8899aa, trailEffect: "slash", screenShake: 0.35 },
    } satisfies AttackAbility, {
      id: "kite-shield-wall",
      name: "Shield Wall",
      kind: "barrier",
      cost: { blue: 2 },
      barrierHp: 30,
    }],
  },
  "buckler": {
    type: "shield",
    id: "buckler",
    name: "Buckler",
    description: "A small, light shield for parrying attacks.",
    rarity: "common",
    sprite: "buckler",
    dimensionId: 0,
    slotCost: { hand: 1 },
    abilities: [{
      id: "buckler-block",
      name: "Block",
      kind: "barrier",
      cost: { blue: 1 },
      barrierHp: 5,
    }, {
      id: "buckler-punch",
      name: "Deflect Punch",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 45, halfAngle: Math.PI / 4 },
      damage: 8,
      knockback: 35,
      visual: { color: 0x8899aa, trailEffect: "slash", screenShake: 0.2 },
    } satisfies AttackAbility],
  },
  "quiver": {
    type: "accessory",
    id: "quiver",
    name: "Quiver",
    description: "A leather quiver. Every finishing shot puts spring back in your step.",
    rarity: "common",
    sprite: "quiver",
    dimensionId: 0,
    slotCost: { accessory: 1 },
    passives: [{ type: "onKillEnergy", blue: 1 }],
  },
  "staff": {
    type: "weapon",
    id: "staff",
    name: "Staff",
    description: "A magical staff that channels arcane energy.",
    rarity: "rare",
    sprite: "staff",
    dimensionId: 0,
    slotCost: { hand: 1, utility: 1 },
    abilities: [{
      id: "staff-blast",
      name: "Arcane Blast",
      kind: "attack",
      cost: { red: 2 },
      shape: { kind: ShapeKind.Circle, radius: 60, range: 200 },
      damage: 25,
      knockback: 0,
      visual: { color: 0x7b68ee, trailEffect: "explosion", screenShake: 0.3 },
    } satisfies AttackAbility, {
      id: "staff-bolt",
      name: "Arcane Bolt",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Point, range: 200 },
      damage: 11,
      knockback: 0,
      visual: { color: 0x7b68ee, trailEffect: "projectile" },
    } satisfies AttackAbility, {
      id: "staff-push",
      name: "Arcane Push",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Sector, radius: 80, halfAngle: Math.PI / 3 },
      damage: 10,
      knockback: 65,
      visual: { color: 0x7b68ee, trailEffect: "explosion", screenShake: 0.25 },
    } satisfies AttackAbility],
    animSet: "staff",
  },
  "spellbook": {
    type: "accessory",
    id: "spellbook",
    name: "Spellbook",
    description: "An ancient tome. Its bearer draws a little more from every rest.",
    rarity: "rare",
    sprite: "spellbook",
    dimensionId: 0,
    slotCost: { accessory: 1 },
    passives: [{ type: "regen", red: 1 }],
  },
  "potion": {
    type: "consumable",
    id: "potion",
    name: "Health Potion",
    description: "A red brew that restores health when consumed. One swig per fight.",
    rarity: "common",
    sprite: "potion",
    dimensionId: 0,
    slotCost: { utility: 1 },
    abilities: [{
      id: "potion-drink",
      name: "Drink Potion",
      kind: "restore",
      cost: {},
      hp: 50,
      uses: 1,
    } satisfies RestoreAbility],
  },
  "bomb": {
    type: "consumable",
    id: "bomb",
    name: "Bomb",
    description: "An explosive device that damages all nearby enemies. You only carry one fuse.",
    rarity: "uncommon",
    sprite: "bomb",
    dimensionId: 0,
    slotCost: { utility: 1 },
    abilities: [{
      id: "bomb-throw",
      name: "Throw Bomb",
      kind: "attack",
      cost: { red: 1 },
      shape: { kind: ShapeKind.Circle, radius: 80, range: 160 },
      damage: 40,
      knockback: 30,
      uses: 1,
      visual: { color: 0xc0392b, trailEffect: "explosion", screenShake: 0.5 },
    } satisfies AttackAbility],
  },
};

// --- Seed ---

export function seedDimension0(): void {
  // Static content is derived from source — re-upsert it on every boot (like seedDimension1/2/3),
  // so changes to enemy templates / items / structures take effect without wiping the database.
  saveDimension(0, "Greenlands", DIMENSION_0_STRUCTURES, "sprites/map-objects/backgrounds/background-grass.png", "sprites/map-decorations");
  // World-0 enemies use use-it-or-lose-it energy (bank factor 1) — they can't stockpile across turns.
  const templates = Object.fromEntries(
    Object.entries(ENEMY_TEMPLATES).map(([k, t]) => [k, { ...t, energyBankFactor: 1 }]),
  );
  saveEnemyTemplates(0, templates);
  saveItems(0, DIMENSION_0_ITEMS);
}
